# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/ed103324-2b43-402d-a116-a0d985a06bb1";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/AD40-7BD1";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/da79d149-8b97-4f9f-88ad-d7174e2989b2";
      fsType = "ext4";
    };

  fileSystems."/mnt/F" = {
    device = "/dev/disk/by-uuid/58FAD50AFAD4E572";
    fsType = "ntfs-3g"; # Ersetze "ext4" durch dein Dateisystem (z. B. "xfs", "btrfs" etc.)
  };
  fileSystems."/mnt/G" = {
    device = "/dev/disk/by-uuid/807ECF0D7ECEFAC4";
    fsType = "ntfs-3g"; # Ersetze "ext4" durch dein Dateisystem (z. B. "xfs", "btrfs" etc.)
  };
    fileSystems."/mnt/Volume" = {
    device = "/dev/disk/by-uuid/861C162C1C16182F";
    fsType = "ntfs-3g"; # Ersetze "ext4" durch dein Dateisystem (z. B. "xfs", "btrfs" etc.)
  };

  swapDevices = [ ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp6s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
